notifications:
  email:
    on_success: never
language: cpp
sudo: required
dist: trusty
env:
  global:
    - NINJA_STATUS="[%p %u/%t@%o %r]"
    - PROJECT_NAME=${PWD##*/}
  matrix:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
before_install:
   - sudo apt-get install -qq cmake || /bin/true
   - sudo apt-get install -qq cppcheck || /bin/true
   - sudo apt-get install -qq doxygen || /bin/true
   - sudo apt-get install -qq git || /bin/true
   - sudo apt-get install -qq lcov || /bin/true
   - sudo apt-get install -qq libboost-filesystem-dev || /bin/true
   - sudo apt-get install -qq libboost-system-dev || /bin/true
   - sudo apt-get install -qq libboost-test-dev || /bin/true
   - sudo apt-get install -qq libboost-thread-dev || /bin/true
   - sudo apt-get install -qq libboost-regex-dev || /bin/true
   - sudo apt-get install -qq libboost-serialization-dev || /bin/true
   - sudo apt-get install -qq libturbojpeg || /bin/true
   - sudo apt-get install -qq ninja-build || /bin/true
   - sudo apt-get install -qq openmpi-bin || /bin/true
   - sudo apt-get install -qq pkg-config || /bin/true
   - sudo apt-get install -qq libhwloc-dev || /bin/true
   - sudo apt-get install -qq avahi-daemon || /bin/true
   - sudo apt-get install -qq libavahi-client-dev || /bin/true
   - sudo apt-get install -qq libleveldb-dev || /bin/true
   - sudo apt-get install -qq libopenmpi-dev || /bin/true
   - sudo apt-get install -qq openmpi-bin || /bin/true
   - sudo apt-get install -qq libmemcached-dev || /bin/true
   - sudo apt-get install -qq libmemcached-tools || /bin/true
   - sudo apt-get install -qq memcached || /bin/true
script:
   - mkdir $BUILD_TYPE
   - cd $BUILD_TYPE
   - cmake -GNinja -DCMAKE_INSTALL_PREFIX=$PWD/install -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
   - ninja all && ninja Tuyau-tests && ninja install
